import { TEMPERATURE_SCALE } from "./constants";
import { formatToTemperature, formatToTemperatureRange } from "./formatters";

function toDomain(forecast) {
  const { date_epoch, day } = forecast;

  return {
    id: date_epoch,
    condition: {
      text: day?.condition.text,
      icon: day?.condition.icon,
    },
    maxTemperature: {
      [TEMPERATURE_SCALE.CELSIUS]: {
        rawValue: day?.maxtemp_c,
        formattedValue: formatToTemperature({
          value: day?.maxtemp_c,
        }),
      },
      [TEMPERATURE_SCALE.FAHRENHEIT]: {
        rawValue: day?.maxtemp_f,
        formattedValue: formatToTemperature({
          scale: TEMPERATURE_SCALE.FAHRENHEIT,
          value: day?.maxtemp_f,
        }),
      },
    },
    minTemperature: {
      [TEMPERATURE_SCALE.CELSIUS]: {
        rawValue: day?.mintemp_c,
        formattedValue: formatToTemperature({
          value: day?.mintemp_c,
        }),
      },
      [TEMPERATURE_SCALE.FAHRENHEIT]: {
        rawValue: day?.mintemp_f,
        formattedValue: formatToTemperature({
          scale: TEMPERATURE_SCALE.FAHRENHEIT,
          value: day?.mintemp_f,
        }),
      },
    },
    rangeTemperature: {
      [TEMPERATURE_SCALE.CELSIUS]: {
        formattedValue: formatToTemperatureRange({
          min: day?.mintemp_c,
          max: day?.maxtemp_c,
        }),
      },
      [TEMPERATURE_SCALE.FAHRENHEIT]: {
        formattedValue: formatToTemperatureRange({
          scale: TEMPERATURE_SCALE.FAHRENHEIT,
          min: day?.mintemp_f,
          max: day?.maxtemp_f,
        }),
      },
    },
  };
}

export const forecastMapper = {
  toDomain,
};

// {
//     "date": "2024-04-05",
//     "date_epoch": 1712275200,
//     "day": {
//         "maxtemp_c": 19.4,
//         "maxtemp_f": 66.9,
//         "mintemp_c": 14.6,
//         "mintemp_f": 58.3,
//         "avgtemp_c": 17,
//         "avgtemp_f": 62.6,
//         "maxwind_mph": 8.5,
//         "maxwind_kph": 13.7,
//         "totalprecip_mm": 0,
//         "totalprecip_in": 0,
//         "totalsnow_cm": 0,
//         "avgvis_km": 10,
//         "avgvis_miles": 6,
//         "avghumidity": 63,
//         "daily_will_it_rain": 0,
//         "daily_chance_of_rain": 0,
//         "daily_will_it_snow": 0,
//         "daily_chance_of_snow": 0,
//         "condition": {
//             "text": "Partly Cloudy ",
//             "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
//             "code": 1003
//         },
//         "uv": 5,
//         "air_quality": {
//             "co": 383.98799999999994,
//             "no2": 25.287999999999997,
//             "o3": 48.84,
//             "so2": 1.5600000000000003,
//             "pm2_5": 13.303999999999998,
//             "pm10": 18.564,
//             "us-epa-index": 1,
//             "gb-defra-index": 2
//         }
//     },
//     "astro": {
//         "sunrise": "07:27 AM",
//         "sunset": "08:21 PM",
//         "moonrise": "05:55 AM",
//         "moonset": "04:22 PM",
//         "moon_phase": "Waning Crescent",
//         "moon_illumination": 20,
//         "is_moon_up": 0,
//         "is_sun_up": 0
//     },
//     "hour": [
//         {
//             "time_epoch": 1712268000,
//             "time": "2024-04-05 00:00",
//             "temp_c": 16,
//             "temp_f": 60.9,
//             "is_day": 0,
//             "condition": {
//                 "text": "Partly Cloudy ",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
//                 "code": 1003
//             },
//             "wind_mph": 7.8,
//             "wind_kph": 12.6,
//             "wind_degree": 239,
//             "wind_dir": "WSW",
//             "pressure_mb": 1019,
//             "pressure_in": 30.1,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 70,
//             "cloud": 59,
//             "feelslike_c": 16.1,
//             "feelslike_f": 60.9,
//             "windchill_c": 16.1,
//             "windchill_f": 60.9,
//             "heatindex_c": 16.1,
//             "heatindex_f": 60.9,
//             "dewpoint_c": 10.7,
//             "dewpoint_f": 51.2,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 12.3,
//             "gust_kph": 19.7,
//             "uv": 1,
//             "air_quality": {
//                 "co": 307.1,
//                 "no2": 19.2,
//                 "o3": 52.9,
//                 "so2": 1.3,
//                 "pm2_5": 23.6,
//                 "pm10": 32.9,
//                 "us-epa-index": 2,
//                 "gb-defra-index": 2
//             }
//         },
//         {
//             "time_epoch": 1712271600,
//             "time": "2024-04-05 01:00",
//             "temp_c": 15.7,
//             "temp_f": 60.2,
//             "is_day": 0,
//             "condition": {
//                 "text": "Clear ",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
//                 "code": 1000
//             },
//             "wind_mph": 7.4,
//             "wind_kph": 11.9,
//             "wind_degree": 238,
//             "wind_dir": "WSW",
//             "pressure_mb": 1019,
//             "pressure_in": 30.09,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 71,
//             "cloud": 21,
//             "feelslike_c": 15.7,
//             "feelslike_f": 60.2,
//             "windchill_c": 15.7,
//             "windchill_f": 60.2,
//             "heatindex_c": 15.7,
//             "heatindex_f": 60.2,
//             "dewpoint_c": 10.5,
//             "dewpoint_f": 50.9,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 11.9,
//             "gust_kph": 19.2,
//             "uv": 1,
//             "air_quality": {
//                 "co": 290.4,
//                 "no2": 15.8,
//                 "o3": 39.3,
//                 "so2": 0.9,
//                 "pm2_5": 24.4,
//                 "pm10": 33.1,
//                 "us-epa-index": 2,
//                 "gb-defra-index": 3
//             }
//         },
//         {
//             "time_epoch": 1712275200,
//             "time": "2024-04-05 02:00",
//             "temp_c": 15.3,
//             "temp_f": 59.5,
//             "is_day": 0,
//             "condition": {
//                 "text": "Clear ",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
//                 "code": 1000
//             },
//             "wind_mph": 7.6,
//             "wind_kph": 12.2,
//             "wind_degree": 242,
//             "wind_dir": "WSW",
//             "pressure_mb": 1019,
//             "pressure_in": 30.08,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 73,
//             "cloud": 7,
//             "feelslike_c": 15.3,
//             "feelslike_f": 59.5,
//             "windchill_c": 15.3,
//             "windchill_f": 59.5,
//             "heatindex_c": 15.3,
//             "heatindex_f": 59.5,
//             "dewpoint_c": 10.6,
//             "dewpoint_f": 51,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 12.5,
//             "gust_kph": 20.2,
//             "uv": 1,
//             "air_quality": {
//                 "co": 277,
//                 "no2": 13.7,
//                 "o3": 27.2,
//                 "so2": 0.6,
//                 "pm2_5": 24.6,
//                 "pm10": 32.7,
//                 "us-epa-index": 2,
//                 "gb-defra-index": 3
//             }
//         },
//         {
//             "time_epoch": 1712278800,
//             "time": "2024-04-05 03:00",
//             "temp_c": 15,
//             "temp_f": 59,
//             "is_day": 0,
//             "condition": {
//                 "text": "Partly Cloudy ",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
//                 "code": 1003
//             },
//             "wind_mph": 6.9,
//             "wind_kph": 11.2,
//             "wind_degree": 255,
//             "wind_dir": "WSW",
//             "pressure_mb": 1019,
//             "pressure_in": 30.08,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 74,
//             "cloud": 26,
//             "feelslike_c": 15,
//             "feelslike_f": 59,
//             "windchill_c": 15,
//             "windchill_f": 59,
//             "heatindex_c": 15,
//             "heatindex_f": 59,
//             "dewpoint_c": 10.4,
//             "dewpoint_f": 50.7,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 11.7,
//             "gust_kph": 18.9,
//             "uv": 1,
//             "air_quality": {
//                 "co": 270.4,
//                 "no2": 13,
//                 "o3": 18.4,
//                 "so2": 0.5,
//                 "pm2_5": 24.5,
//                 "pm10": 32.1,
//                 "us-epa-index": 2,
//                 "gb-defra-index": 3
//             }
//         },
//         {
//             "time_epoch": 1712282400,
//             "time": "2024-04-05 04:00",
//             "temp_c": 14.7,
//             "temp_f": 58.5,
//             "is_day": 0,
//             "condition": {
//                 "text": "Partly Cloudy ",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
//                 "code": 1003
//             },
//             "wind_mph": 6,
//             "wind_kph": 9.7,
//             "wind_degree": 253,
//             "wind_dir": "WSW",
//             "pressure_mb": 1019,
//             "pressure_in": 30.08,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 74,
//             "cloud": 49,
//             "feelslike_c": 14.3,
//             "feelslike_f": 57.7,
//             "windchill_c": 14.3,
//             "windchill_f": 57.7,
//             "heatindex_c": 14.7,
//             "heatindex_f": 58.5,
//             "dewpoint_c": 10.1,
//             "dewpoint_f": 50.2,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 10.5,
//             "gust_kph": 16.9,
//             "uv": 1,
//             "air_quality": {
//                 "co": 270.4,
//                 "no2": 13.5,
//                 "o3": 11.4,
//                 "so2": 0.4,
//                 "pm2_5": 23.5,
//                 "pm10": 30.6,
//                 "us-epa-index": 2,
//                 "gb-defra-index": 2
//             }
//         },
//         {
//             "time_epoch": 1712286000,
//             "time": "2024-04-05 05:00",
//             "temp_c": 14.7,
//             "temp_f": 58.4,
//             "is_day": 0,
//             "condition": {
//                 "text": "Clear ",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
//                 "code": 1000
//             },
//             "wind_mph": 5.8,
//             "wind_kph": 9.4,
//             "wind_degree": 250,
//             "wind_dir": "WSW",
//             "pressure_mb": 1019,
//             "pressure_in": 30.09,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 73,
//             "cloud": 20,
//             "feelslike_c": 14.3,
//             "feelslike_f": 57.8,
//             "windchill_c": 14.3,
//             "windchill_f": 57.8,
//             "heatindex_c": 14.7,
//             "heatindex_f": 58.4,
//             "dewpoint_c": 10,
//             "dewpoint_f": 50,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 10,
//             "gust_kph": 16.1,
//             "uv": 1,
//             "air_quality": {
//                 "co": 310.4,
//                 "no2": 17.8,
//                 "o3": 3.7,
//                 "so2": 0.6,
//                 "pm2_5": 22.6,
//                 "pm10": 29.2,
//                 "us-epa-index": 2,
//                 "gb-defra-index": 2
//             }
//         },
//         {
//             "time_epoch": 1712289600,
//             "time": "2024-04-05 06:00",
//             "temp_c": 14.8,
//             "temp_f": 58.6,
//             "is_day": 0,
//             "condition": {
//                 "text": "Clear ",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
//                 "code": 1000
//             },
//             "wind_mph": 5.4,
//             "wind_kph": 8.6,
//             "wind_degree": 240,
//             "wind_dir": "WSW",
//             "pressure_mb": 1019,
//             "pressure_in": 30.1,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 73,
//             "cloud": 7,
//             "feelslike_c": 14.5,
//             "feelslike_f": 58.1,
//             "windchill_c": 14.5,
//             "windchill_f": 58.1,
//             "heatindex_c": 14.8,
//             "heatindex_f": 58.6,
//             "dewpoint_c": 10,
//             "dewpoint_f": 50,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 8.9,
//             "gust_kph": 14.3,
//             "uv": 1,
//             "air_quality": {
//                 "co": 363.8,
//                 "no2": 20.4,
//                 "o3": 0.4,
//                 "so2": 0.8,
//                 "pm2_5": 22.1,
//                 "pm10": 28.3,
//                 "us-epa-index": 2,
//                 "gb-defra-index": 2
//             }
//         },
//         {
//             "time_epoch": 1712293200,
//             "time": "2024-04-05 07:00",
//             "temp_c": 15.8,
//             "temp_f": 60.4,
//             "is_day": 0,
//             "condition": {
//                 "text": "Clear ",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
//                 "code": 1000
//             },
//             "wind_mph": 5.8,
//             "wind_kph": 9.4,
//             "wind_degree": 243,
//             "wind_dir": "WSW",
//             "pressure_mb": 1020,
//             "pressure_in": 30.12,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 70,
//             "cloud": 12,
//             "feelslike_c": 15.8,
//             "feelslike_f": 60.4,
//             "windchill_c": 15.8,
//             "windchill_f": 60.4,
//             "heatindex_c": 15.8,
//             "heatindex_f": 60.4,
//             "dewpoint_c": 10.4,
//             "dewpoint_f": 50.7,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 8.1,
//             "gust_kph": 13.1,
//             "uv": 1,
//             "air_quality": {
//                 "co": 413.9,
//                 "no2": 21.8,
//                 "o3": 1.2,
//                 "so2": 0.9,
//                 "pm2_5": 21.6,
//                 "pm10": 27.5,
//                 "us-epa-index": 2,
//                 "gb-defra-index": 2
//             }
//         },
//         {
//             "time_epoch": 1712296800,
//             "time": "2024-04-05 08:00",
//             "temp_c": 16.7,
//             "temp_f": 62.1,
//             "is_day": 1,
//             "condition": {
//                 "text": "Sunny",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
//                 "code": 1000
//             },
//             "wind_mph": 6.3,
//             "wind_kph": 10.1,
//             "wind_degree": 233,
//             "wind_dir": "SW",
//             "pressure_mb": 1021,
//             "pressure_in": 30.14,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 65,
//             "cloud": 22,
//             "feelslike_c": 16.7,
//             "feelslike_f": 62.1,
//             "windchill_c": 16.7,
//             "windchill_f": 62.1,
//             "heatindex_c": 16.7,
//             "heatindex_f": 62.1,
//             "dewpoint_c": 10,
//             "dewpoint_f": 50.1,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 8.2,
//             "gust_kph": 13.1,
//             "uv": 5,
//             "air_quality": {
//                 "co": 420.6,
//                 "no2": 21.1,
//                 "o3": 6,
//                 "so2": 1,
//                 "pm2_5": 20,
//                 "pm10": 25.6,
//                 "us-epa-index": 2,
//                 "gb-defra-index": 2
//             }
//         },
//         {
//             "time_epoch": 1712300400,
//             "time": "2024-04-05 09:00",
//             "temp_c": 17.5,
//             "temp_f": 63.6,
//             "is_day": 1,
//             "condition": {
//                 "text": "Sunny",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
//                 "code": 1000
//             },
//             "wind_mph": 7.2,
//             "wind_kph": 11.5,
//             "wind_degree": 225,
//             "wind_dir": "SW",
//             "pressure_mb": 1021,
//             "pressure_in": 30.15,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 60,
//             "cloud": 18,
//             "feelslike_c": 17.5,
//             "feelslike_f": 63.6,
//             "windchill_c": 17.5,
//             "windchill_f": 63.6,
//             "heatindex_c": 17.5,
//             "heatindex_f": 63.6,
//             "dewpoint_c": 9.8,
//             "dewpoint_f": 49.7,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 9,
//             "gust_kph": 14.5,
//             "uv": 5,
//             "air_quality": {
//                 "co": 380.5,
//                 "no2": 20.2,
//                 "o3": 17.7,
//                 "so2": 1,
//                 "pm2_5": 18.1,
//                 "pm10": 23.4,
//                 "us-epa-index": 2,
//                 "gb-defra-index": 2
//             }
//         },
//         {
//             "time_epoch": 1712304000,
//             "time": "2024-04-05 10:00",
//             "temp_c": 16,
//             "temp_f": 60.8,
//             "is_day": 1,
//             "condition": {
//                 "text": "Sunny",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
//                 "code": 1000
//             },
//             "wind_mph": 2.2,
//             "wind_kph": 3.6,
//             "wind_degree": 217,
//             "wind_dir": "SW",
//             "pressure_mb": 1020,
//             "pressure_in": 30.12,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 72,
//             "cloud": 0,
//             "feelslike_c": 18.2,
//             "feelslike_f": 64.7,
//             "windchill_c": 18.2,
//             "windchill_f": 64.7,
//             "heatindex_c": 18.2,
//             "heatindex_f": 64.7,
//             "dewpoint_c": 9.7,
//             "dewpoint_f": 49.5,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 9.2,
//             "gust_kph": 14.8,
//             "uv": 5,
//             "air_quality": {
//                 "co": 243.7,
//                 "no2": 6.4,
//                 "o3": 95.8,
//                 "so2": 0.7,
//                 "pm2_5": 6.3,
//                 "pm10": 9.5,
//                 "us-epa-index": 1,
//                 "gb-defra-index": 1
//             }
//         },
//         {
//             "time_epoch": 1712307600,
//             "time": "2024-04-05 11:00",
//             "temp_c": 18.7,
//             "temp_f": 65.6,
//             "is_day": 1,
//             "condition": {
//                 "text": "Partly Cloudy ",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
//                 "code": 1003
//             },
//             "wind_mph": 7.2,
//             "wind_kph": 11.5,
//             "wind_degree": 213,
//             "wind_dir": "SSW",
//             "pressure_mb": 1021,
//             "pressure_in": 30.14,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 55,
//             "cloud": 32,
//             "feelslike_c": 18.7,
//             "feelslike_f": 65.6,
//             "windchill_c": 18.7,
//             "windchill_f": 65.6,
//             "heatindex_c": 18.7,
//             "heatindex_f": 65.6,
//             "dewpoint_c": 9.6,
//             "dewpoint_f": 49.3,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 8.8,
//             "gust_kph": 14.2,
//             "uv": 5,
//             "air_quality": {
//                 "co": 227,
//                 "no2": 3.6,
//                 "o3": 110.2,
//                 "so2": 0.6,
//                 "pm2_5": 5.1,
//                 "pm10": 7.7,
//                 "us-epa-index": 1,
//                 "gb-defra-index": 1
//             }
//         },
//         {
//             "time_epoch": 1712311200,
//             "time": "2024-04-05 12:00",
//             "temp_c": 19,
//             "temp_f": 66.2,
//             "is_day": 1,
//             "condition": {
//                 "text": "Overcast ",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
//                 "code": 1009
//             },
//             "wind_mph": 7.4,
//             "wind_kph": 11.9,
//             "wind_degree": 204,
//             "wind_dir": "SSW",
//             "pressure_mb": 1020,
//             "pressure_in": 30.12,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 53,
//             "cloud": 100,
//             "feelslike_c": 19,
//             "feelslike_f": 66.2,
//             "windchill_c": 19,
//             "windchill_f": 66.2,
//             "heatindex_c": 19,
//             "heatindex_f": 66.2,
//             "dewpoint_c": 9.4,
//             "dewpoint_f": 48.9,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 9.2,
//             "gust_kph": 14.9,
//             "uv": 4,
//             "air_quality": {
//                 "co": 223.6,
//                 "no2": 2.6,
//                 "o3": 117.3,
//                 "so2": 0.5,
//                 "pm2_5": 4.3,
//                 "pm10": 6.6,
//                 "us-epa-index": 1,
//                 "gb-defra-index": 1
//             }
//         },
//         {
//             "time_epoch": 1712314800,
//             "time": "2024-04-05 13:00",
//             "temp_c": 19.2,
//             "temp_f": 66.6,
//             "is_day": 1,
//             "condition": {
//                 "text": "Overcast ",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
//                 "code": 1009
//             },
//             "wind_mph": 8.1,
//             "wind_kph": 13,
//             "wind_degree": 201,
//             "wind_dir": "SSW",
//             "pressure_mb": 1020,
//             "pressure_in": 30.12,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 53,
//             "cloud": 91,
//             "feelslike_c": 19.2,
//             "feelslike_f": 66.6,
//             "windchill_c": 19.2,
//             "windchill_f": 66.6,
//             "heatindex_c": 19.2,
//             "heatindex_f": 66.6,
//             "dewpoint_c": 9.4,
//             "dewpoint_f": 48.9,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 10.1,
//             "gust_kph": 16.3,
//             "uv": 4,
//             "air_quality": {
//                 "co": 217,
//                 "no2": 2.1,
//                 "o3": 118.7,
//                 "so2": 0.4,
//                 "pm2_5": 3.5,
//                 "pm10": 5.5,
//                 "us-epa-index": 1,
//                 "gb-defra-index": 1
//             }
//         },
//         {
//             "time_epoch": 1712318400,
//             "time": "2024-04-05 14:00",
//             "temp_c": 19.2,
//             "temp_f": 66.5,
//             "is_day": 1,
//             "condition": {
//                 "text": "Overcast ",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
//                 "code": 1009
//             },
//             "wind_mph": 8.3,
//             "wind_kph": 13.3,
//             "wind_degree": 201,
//             "wind_dir": "SSW",
//             "pressure_mb": 1019,
//             "pressure_in": 30.1,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 53,
//             "cloud": 100,
//             "feelslike_c": 19.2,
//             "feelslike_f": 66.5,
//             "windchill_c": 19.2,
//             "windchill_f": 66.5,
//             "heatindex_c": 19.2,
//             "heatindex_f": 66.5,
//             "dewpoint_c": 9.5,
//             "dewpoint_f": 49.1,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 10.3,
//             "gust_kph": 16.6,
//             "uv": 4,
//             "air_quality": {
//                 "co": 220.3,
//                 "no2": 2.3,
//                 "o3": 118.7,
//                 "so2": 0.4,
//                 "pm2_5": 3.2,
//                 "pm10": 5.1,
//                 "us-epa-index": 1,
//                 "gb-defra-index": 1
//             }
//         },
//         {
//             "time_epoch": 1712322000,
//             "time": "2024-04-05 15:00",
//             "temp_c": 19.1,
//             "temp_f": 66.3,
//             "is_day": 1,
//             "condition": {
//                 "text": "Overcast ",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
//                 "code": 1009
//             },
//             "wind_mph": 7.2,
//             "wind_kph": 11.5,
//             "wind_degree": 207,
//             "wind_dir": "SSW",
//             "pressure_mb": 1019,
//             "pressure_in": 30.09,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 53,
//             "cloud": 100,
//             "feelslike_c": 19.1,
//             "feelslike_f": 66.3,
//             "windchill_c": 19.1,
//             "windchill_f": 66.3,
//             "heatindex_c": 19.1,
//             "heatindex_f": 66.3,
//             "dewpoint_c": 9.4,
//             "dewpoint_f": 48.9,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 9.1,
//             "gust_kph": 14.6,
//             "uv": 4,
//             "air_quality": {
//                 "co": 223.6,
//                 "no2": 3.2,
//                 "o3": 115.9,
//                 "so2": 0.5,
//                 "pm2_5": 3.1,
//                 "pm10": 5.3,
//                 "us-epa-index": 1,
//                 "gb-defra-index": 1
//             }
//         },
//         {
//             "time_epoch": 1712325600,
//             "time": "2024-04-05 16:00",
//             "temp_c": 18.9,
//             "temp_f": 66,
//             "is_day": 1,
//             "condition": {
//                 "text": "Partly Cloudy ",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
//                 "code": 1003
//             },
//             "wind_mph": 6.7,
//             "wind_kph": 10.8,
//             "wind_degree": 200,
//             "wind_dir": "SSW",
//             "pressure_mb": 1019,
//             "pressure_in": 30.09,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 54,
//             "cloud": 44,
//             "feelslike_c": 18.9,
//             "feelslike_f": 66,
//             "windchill_c": 18.9,
//             "windchill_f": 66,
//             "heatindex_c": 18.9,
//             "heatindex_f": 66,
//             "dewpoint_c": 9.3,
//             "dewpoint_f": 48.8,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 8.8,
//             "gust_kph": 14.2,
//             "uv": 5,
//             "air_quality": {
//                 "co": 243.7,
//                 "no2": 6.9,
//                 "o3": 105.9,
//                 "so2": 1,
//                 "pm2_5": 4.1,
//                 "pm10": 7.5,
//                 "us-epa-index": 1,
//                 "gb-defra-index": 1
//             }
//         },
//         {
//             "time_epoch": 1712329200,
//             "time": "2024-04-05 17:00",
//             "temp_c": 18.3,
//             "temp_f": 65,
//             "is_day": 1,
//             "condition": {
//                 "text": "Sunny",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
//                 "code": 1000
//             },
//             "wind_mph": 5.6,
//             "wind_kph": 9,
//             "wind_degree": 191,
//             "wind_dir": "SSW",
//             "pressure_mb": 1019,
//             "pressure_in": 30.09,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 56,
//             "cloud": 22,
//             "feelslike_c": 18.3,
//             "feelslike_f": 65,
//             "windchill_c": 18.3,
//             "windchill_f": 65,
//             "heatindex_c": 18.3,
//             "heatindex_f": 65,
//             "dewpoint_c": 9.4,
//             "dewpoint_f": 48.9,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 7.7,
//             "gust_kph": 12.4,
//             "uv": 5,
//             "air_quality": {
//                 "co": 297.1,
//                 "no2": 14.1,
//                 "o3": 90.1,
//                 "so2": 1.8,
//                 "pm2_5": 5.4,
//                 "pm10": 10.3,
//                 "us-epa-index": 1,
//                 "gb-defra-index": 1
//             }
//         },
//         {
//             "time_epoch": 1712332800,
//             "time": "2024-04-05 18:00",
//             "temp_c": 17.6,
//             "temp_f": 63.7,
//             "is_day": 1,
//             "condition": {
//                 "text": "Partly Cloudy ",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
//                 "code": 1003
//             },
//             "wind_mph": 4.5,
//             "wind_kph": 7.2,
//             "wind_degree": 181,
//             "wind_dir": "S",
//             "pressure_mb": 1019,
//             "pressure_in": 30.1,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 60,
//             "cloud": 33,
//             "feelslike_c": 17.6,
//             "feelslike_f": 63.7,
//             "windchill_c": 17.6,
//             "windchill_f": 63.7,
//             "heatindex_c": 17.6,
//             "heatindex_f": 63.7,
//             "dewpoint_c": 9.7,
//             "dewpoint_f": 49.5,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 6.4,
//             "gust_kph": 10.3,
//             "uv": 5,
//             "air_quality": {
//                 "co": 373.8,
//                 "no2": 25.4,
//                 "o3": 73.7,
//                 "so2": 3,
//                 "pm2_5": 6.5,
//                 "pm10": 12.2,
//                 "us-epa-index": 1,
//                 "gb-defra-index": 1
//             }
//         },
//         {
//             "time_epoch": 1712336400,
//             "time": "2024-04-05 19:00",
//             "temp_c": 17,
//             "temp_f": 62.6,
//             "is_day": 1,
//             "condition": {
//                 "text": "Partly Cloudy ",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
//                 "code": 1003
//             },
//             "wind_mph": 2.5,
//             "wind_kph": 4,
//             "wind_degree": 183,
//             "wind_dir": "S",
//             "pressure_mb": 1020,
//             "pressure_in": 30.11,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 63,
//             "cloud": 58,
//             "feelslike_c": 17,
//             "feelslike_f": 62.6,
//             "windchill_c": 17,
//             "windchill_f": 62.6,
//             "heatindex_c": 17,
//             "heatindex_f": 62.6,
//             "dewpoint_c": 10,
//             "dewpoint_f": 50.1,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 3.7,
//             "gust_kph": 5.9,
//             "uv": 5,
//             "air_quality": {
//                 "co": 574.1,
//                 "no2": 53.5,
//                 "o3": 44.4,
//                 "so2": 5.5,
//                 "pm2_5": 9.7,
//                 "pm10": 16.8,
//                 "us-epa-index": 1,
//                 "gb-defra-index": 1
//             }
//         },
//         {
//             "time_epoch": 1712340000,
//             "time": "2024-04-05 20:00",
//             "temp_c": 16.7,
//             "temp_f": 62,
//             "is_day": 1,
//             "condition": {
//                 "text": "Overcast ",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
//                 "code": 1009
//             },
//             "wind_mph": 0.7,
//             "wind_kph": 1.1,
//             "wind_degree": 159,
//             "wind_dir": "SSE",
//             "pressure_mb": 1020,
//             "pressure_in": 30.12,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 65,
//             "cloud": 100,
//             "feelslike_c": 16.7,
//             "feelslike_f": 62,
//             "windchill_c": 16.7,
//             "windchill_f": 62,
//             "heatindex_c": 16.7,
//             "heatindex_f": 62,
//             "dewpoint_c": 10,
//             "dewpoint_f": 50,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 1.1,
//             "gust_kph": 1.7,
//             "uv": 4,
//             "air_quality": {
//                 "co": 774.4,
//                 "no2": 81.6,
//                 "o3": 18.8,
//                 "so2": 6.4,
//                 "pm2_5": 14.2,
//                 "pm10": 22.4,
//                 "us-epa-index": 1,
//                 "gb-defra-index": 2
//             }
//         },
//         {
//             "time_epoch": 1712343600,
//             "time": "2024-04-05 21:00",
//             "temp_c": 16.4,
//             "temp_f": 61.4,
//             "is_day": 0,
//             "condition": {
//                 "text": "Overcast ",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
//                 "code": 1009
//             },
//             "wind_mph": 0.7,
//             "wind_kph": 1.1,
//             "wind_degree": 67,
//             "wind_dir": "ENE",
//             "pressure_mb": 1020,
//             "pressure_in": 30.13,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 64,
//             "cloud": 100,
//             "feelslike_c": 16.4,
//             "feelslike_f": 61.4,
//             "windchill_c": 16.4,
//             "windchill_f": 61.4,
//             "heatindex_c": 16.4,
//             "heatindex_f": 61.4,
//             "dewpoint_c": 9.7,
//             "dewpoint_f": 49.4,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 1.1,
//             "gust_kph": 1.8,
//             "uv": 1,
//             "air_quality": {
//                 "co": 814.4,
//                 "no2": 86.4,
//                 "o3": 9.6,
//                 "so2": 4.7,
//                 "pm2_5": 17,
//                 "pm10": 25.2,
//                 "us-epa-index": 2,
//                 "gb-defra-index": 2
//             }
//         },
//         {
//             "time_epoch": 1712347200,
//             "time": "2024-04-05 22:00",
//             "temp_c": 16.2,
//             "temp_f": 61.1,
//             "is_day": 0,
//             "condition": {
//                 "text": "Cloudy ",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
//                 "code": 1006
//             },
//             "wind_mph": 2.2,
//             "wind_kph": 3.6,
//             "wind_degree": 51,
//             "wind_dir": "NE",
//             "pressure_mb": 1020,
//             "pressure_in": 30.13,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 64,
//             "cloud": 70,
//             "feelslike_c": 16.2,
//             "feelslike_f": 61.1,
//             "windchill_c": 16.2,
//             "windchill_f": 61.1,
//             "heatindex_c": 16.2,
//             "heatindex_f": 61.1,
//             "dewpoint_c": 9.3,
//             "dewpoint_f": 48.7,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 3.8,
//             "gust_kph": 6.2,
//             "uv": 1,
//             "air_quality": {
//                 "co": 714.3,
//                 "no2": 69.9,
//                 "o3": 10.4,
//                 "so2": 2.8,
//                 "pm2_5": 17.3,
//                 "pm10": 24.6,
//                 "us-epa-index": 2,
//                 "gb-defra-index": 2
//             }
//         },
//         {
//             "time_epoch": 1712350800,
//             "time": "2024-04-05 23:00",
//             "temp_c": 16,
//             "temp_f": 60.7,
//             "is_day": 0,
//             "condition": {
//                 "text": "Overcast ",
//                 "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
//                 "code": 1009
//             },
//             "wind_mph": 3.6,
//             "wind_kph": 5.8,
//             "wind_degree": 57,
//             "wind_dir": "ENE",
//             "pressure_mb": 1020,
//             "pressure_in": 30.12,
//             "precip_mm": 0,
//             "precip_in": 0,
//             "snow_cm": 0,
//             "humidity": 62,
//             "cloud": 93,
//             "feelslike_c": 16,
//             "feelslike_f": 60.7,
//             "windchill_c": 16,
//             "windchill_f": 60.7,
//             "heatindex_c": 16,
//             "heatindex_f": 60.7,
//             "dewpoint_c": 8.8,
//             "dewpoint_f": 47.8,
//             "will_it_rain": 0,
//             "chance_of_rain": 0,
//             "will_it_snow": 0,
//             "chance_of_snow": 0,
//             "vis_km": 10,
//             "vis_miles": 6,
//             "gust_mph": 6.3,
//             "gust_kph": 10.2,
//             "uv": 1,
//             "air_quality": {
//                 "co": 574.1,
//                 "no2": 49.4,
//                 "o3": 17.2,
//                 "so2": 1.7,
//                 "pm2_5": 15.7,
//                 "pm10": 21.7,
//                 "us-epa-index": 2,
//                 "gb-defra-index": 2
//             }
//         }
//     ]
// }
